### ISSUE TITLE
Feature Requests

### ISSUE THREAD

**Issue by commy2** [CBATeam/CBA_A3#1284]
- [ ] CBA based project template #1033
- [ ] Filtered getUnitLoadout #1236
- [ ] ExtensionCallback helpers #1196
- [ ] Customizable Dialog function #1169
- [ ] settings control API #1115
- [ ] `CBA_statemachine_fnc_addCompoundState` #1082

**Comment by commy2** [comment]
If your requests ends up in the OP, consider it recognized (without any eta's or guarantees of course).

If you have a request, make your case for it in a separate issue.
